### ISSUE TITLE
Tilt as dependency?

### ISSUE THREAD

**Issue by jacquescrocker** [trvsdnn/frank#9]
sorry for all the tickets. I'll post patches soon I promise!

any reason for tilt to be vendored? Would you be ok with it as a gem dependency if I do the work of swapping it out?

Thanks again!

**Comment by trvsdnn** [comment]
Tilt is bundled because we had to patch it to accept a string instead of a filename. This was necessary to get the META field support working within templates. I would love to have it as a dependency, but I couldn't find an elegant way to support the meta fields without the patch to tilt.

If you come up with something, i'm all about making it a dependency.

**Comment by jacquescrocker** [comment]
sweet. i'll get crackin! ;-)

**Comment by jacquescrocker** [comment]
Ok, I got it working. The trick is to invoke tilt like this:

```
Tilt.new{source} 
```

instead of 

```
Tilt.new(source)
```

This allows you to customize the input loading.

I made the changes and tested it in my own project. Works great, but the specs dont pass. I'll keep hacking on it.

http://github.com/railsjedi/frank/commit/c8d7c01c2b1be830f8bbaa1e49c15f206a7c44e1

**Comment by trvsdnn** [comment]
Looks good man, I could probably merge in the tilt disconnect tomorrow if specs are passing and all.

**Comment by jacquescrocker** [comment]
sweet, thanks man!

**Comment by jacquescrocker** [comment]
Fixed in http://github.com/blahed/frank/tree/0.4.x
